version: '3'
services:
  mysql:
    image: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: #
      MYSQL_DATABASE: #
      MYSQL_USER: #
      MYSQL_PASSWORD: #
    restart: always
  wordpress:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - ./wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: #
      MYSQL_ROOT_PASSWORD: #
      WORDPRESS_DB_NAME: #
      WORDPRESS_DB_USER: #
      WORDPRESS_DB_PASSWORD: #
      WORDPRESS_TABLE_PREFIX: #
    links:
      - mysql
    restart: always
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: #
      PMA_USER: #
      PMA_PASSWORD: #
    ports:
      - "5000:80"
